### ISSUE TITLE
Missing `data/uploaded` folder in the Docker

### ISSUE THREAD

**Issue by VPetukhov** [euxhenh/cellar#8]
Thank you for developing this amazing tool! 
I'm trying to deploy it for our datasets, and simply using the docker throws an error on dataset upload:
```
docker run --rm -p 8050:8050 -v /home/azureuser/data:/home/nonroot/cellar/data euxhen/cellar
```
> ERROR: Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/nonroot/.conda/envs/cellar/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nonroot/.conda/envs/cellar/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nonroot/.conda/envs/cellar/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nonroot/.conda/envs/cellar/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/nonroot/.conda/envs/cellar/lib/python3.8/site-packages/dash/dash.py", line 1383, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/home/nonroot/.conda/envs/cellar/lib/python3.8/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/home/nonroot/cellar/controller/data_uploader.py", line 46, in upload_data
    with open(os.path.join(DATA_PATH, 'uploaded', filename), "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/uploaded/processed.h5ad'

If I log in to the container (`docker run --rm -p 8050:8050 -v /home/azureuser/data:/home/nonroot/cellar/data -it --entrypoint /bin/bash euxhen/cellar`) and create a subfolder manually (`mkdir data/uploaded`), it starts working fine.

**UPDATE:** I just realized that the problem was in the `-v /home/azureuser/data:/home/nonroot/cellar/data` part. It overrides the whole `data` folder, which is incorrect. Instead, the data folder should be mounted to `/home/nonroot/cellar/data/server`. So the solution would be to [update the documentation](https://euxhenh.github.io/cellar/#local-installation-docker), describing that either the mounted directory should have subfolders `server` and `uploaded`, or that it should be mounted to `/home/nonroot/cellar/data/server`.

**UPDATE 2:** Looking at other content of the `data` folder, it looks like normal functioning of Cellar requires the following files:
```
data/ASCT-B_tables
data/geneIdsNamesHuman.csv
data/geneIdsNamesMouse.csv
```
So, full mounting of the `data` folder should not be recommended, I guess?

**Comment by euxhenh** [comment]
Hi,

Yes, the documentation is incorrect. The mount directory should be `/home/nonroot/cellar/data/server`.

Thank you for discovering this! I will update the docs ASAP.

Cheers!
